namePath:
  name: name
  in: path
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  required: true
  schema:
    type: string
daysPath:
  name: days
  in: path
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  required: true
  schema:
    type: integer
descriptionPath:
  name: description
  in: path
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  schema:
    type: string
nameQuery:
  name: name
  in: query
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  schema:
    type: string
daysQuery:
  name: days
  in: query
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  schema:
    type: integer
descriptionQuery:
  name: description
  in: query
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
  schema:
    type: string